### PR TITLE
Preview: Use gogoproto to generate Go code

### PR DESCRIPTION
**Pull request by owais**
This generates the Go code with gogoproto instead of the default Go protobuf implementation. When merged, this should be released as the next major version as it can break the Go programs depending on this library.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@owais the build failed, is this expected?

**Comment by owais** [comment]
The build seems to be failing because of a newer version of bazel that has deprecated some features. I'll try to look into it tomorrow.

**Comment by songy23** [comment]
@owais https://github.com/census-instrumentation/opencensus-proto/pull/206 should fix it.

**Comment by owais** [comment]
Fixed the travis build in: https://github.com/census-instrumentation/opencensus-proto/pull/207

**Pull request closed without merging**
