### PR TITLE
Update gen-go files.

### PR DESCRIPTION
**Pull request by songy23**

### CODE REVIEW

**Comment by rakyll** [comment]
Is this breaking opencensusd? If so, can we also have a PR fixing it?

**Comment by songy23** [comment]
> Is this breaking opencensusd? If so, can we also have a PR fixing it?

Yes, I will send a PR to fix the import path for OC-Service after this PR.

**Comment by songy23** [comment]
Updated, PTAL.

OC-D import will be fixed with https://github.com/census-instrumentation/opencensus-service/pull/17.

**Comment by songy23** [comment]
Thanks!

**Pull request merged**
